# https://leetcode.com/problems/find-the-difference/
#
# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        tList = list(t)
        for ch in s:
            tList.remove(ch)
        return tList.pop(0)


if __name__ == "__main__":
    solution = Solution()
    print(solution.findTheDifference("abcd","abcde"))
